# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-deployment
  labels:
    app: bookapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
        - name: bookapi
          image: zaibaki/bookapi:main
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"